import Image from "next/image";
import Link from "next/link";
import { ArtworkSlot } from "@/components/artwork-slot";
import { artwork, frogUnits, lionUnits, trailer } from "@/lib/site";

const modes = [
  { slug: "campaign", label: "Solo", title: "Campaign", lines: ["Fight through escalating missions.", "Master both sides.", "Meet the problem at the end."], note: "Situation developing." },
  { slug: "multiplayer", label: "PVP", title: "Multiplayer", lines: ["Build your wall.", "Send your balloons.", "Break theirs first."], note: "Someone will regret this." },
  { slug: "sandbox", label: "Free play", title: "Sandbox", lines: ["Build anything.", "Test everything.", "See what happens."], note: "Supervision not provided." },
];
export function PortalHero() {
  return <section className="portal-hero" aria-labelledby="portal-title"><div className="portal-hero-copy"><p className="eyebrow">Frogs defend. Lions ascend.</p><h1 id="portal-title">FLOAT</h1><p className="hero-mantra">Build.<br />Defend.<br />Ascend.</p><p className="hero-date">Coming October 2026</p><a className="portal-start" href="#modes">Choose your mode <span aria-hidden="true">↓</span></a></div><ArtworkSlot asset={artwork.hero} className="portal-key-art" preload sizes="(max-width: 700px) 100vw, 58vw" position="50% 48%" /></section>;
}
export function ModeDoors() {
  return <section className="portal-modes" id="modes" aria-labelledby="modes-title"><div className="portal-section-heading"><div><p className="eyebrow">Pick your kind of trouble</p><h2 id="modes-title">Three ways into Float.</h2></div><span className="eyebrow">One very disputed sky.</span></div><div className="mode-doors">{modes.map((mode, index) => <Link className={`mode-door mode-${mode.slug}`} href={`/${mode.slug}`} key={mode.slug} aria-labelledby={`${mode.slug}-title`} aria-describedby={`${mode.slug}-copy`}><div className="mode-art">{mode.slug === "multiplayer" ? <><ArtworkSlot asset={artwork.frogs} className="split-frogs" position="30% 48%" sizes="(max-width: 700px) 48vw, 16vw" /><ArtworkSlot asset={artwork.lions} className="split-lions" position="38% 45%" sizes="(max-width: 700px) 48vw, 16vw" /><span className="versus" aria-hidden="true">VS</span></> : <ArtworkSlot asset={mode.slug === "campaign" ? artwork.campaign : artwork.frogs} position={mode.slug === "campaign" ? "50% 72%" : "45% 58%"} preload={mode.slug === "campaign"} sizes="(max-width: 700px) 94vw, 32vw" />}<span className="mode-number" aria-hidden="true">0{index + 1}</span><span className="mode-label eyebrow">{mode.label}</span></div><div className="mode-copy"><div className="mode-title-row"><h3 id={`${mode.slug}-title`}>{mode.title}</h3><span className="mode-arrow" aria-hidden="true">↗</span></div><p id={`${mode.slug}-copy`}>{mode.lines.map(line => <span key={line}>{line}</span>)}</p><p className="mode-note">{mode.note}</p></div></Link>)}</div></section>;
}
export function GameGlimpse() {
  return <section className="game-glimpse" aria-labelledby="glimpse-title"><div className="glimpse-heading"><h2 id="glimpse-title" className="eyebrow">Known assets</h2><p>Frogs defend. Lions ascend.</p></div><div className="glimpse-sides">{[{ title: "Frogs", asset: artwork.frogs, units: frogUnits, position: "30% 52%", role: "Ground crew" }, { title: "Lions", asset: artwork.lions, units: lionUnits, position: "50% 42%", role: "Air traffic" }].map(side => <figure className="glimpse-side" key={side.title}><ArtworkSlot asset={side.asset} position={side.position} sizes="(max-width: 700px) 94vw, 45vw" /><figcaption><div><h3>{side.title}</h3><span className="eyebrow">{side.role}</span></div><p>{side.units.map(unit => unit.alt).join(" / ")}</p></figcaption></figure>)}</div></section>;
}
export function PortalCinematic() {
  return <section className="portal-cinematic" aria-labelledby="cinematic-title"><div className="portal-section-heading"><h2 id="cinematic-title">Float cinematic</h2><span className="eyebrow">{trailer.embedUrl || trailer.src ? "Now showing" : "Coming soon"}</span></div><div className="portal-screen">{trailer.embedUrl ? <iframe src={trailer.embedUrl} title="Float cinematic" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen loading="lazy" /> : trailer.src ? <video controls preload="none" poster={trailer.poster} aria-label="Float cinematic"><source src={trailer.src} /></video> : <div className="portal-screen-placeholder"><span className="eyebrow">Float / Tenet Studios</span><div><p>FLOAT</p><span className="eyebrow">Cinematic coming soon</span></div><span className="eyebrow">The sky is only the beginning.</span></div>}</div></section>;
}
export function PortalRelease() {
  return <section className="portal-release" aria-labelledby="release-title"><Image src="/images/hero/float-key-art.png" alt="" fill sizes="100vw" className="release-sky" /><div><h2 id="release-title">FLOAT</h2><p>Coming October 2026</p><div className="portal-stores" aria-label="Store availability"><button disabled>App Store<small>Coming soon</small></button><button disabled>Google Play<small>Coming soon</small></button></div><small>The sky situation remains unresolved.</small></div></section>;
}
